---
title: "simple data transform"
output: html_document
---


```{r}
library(tidyverse)
library(here)
library(skimr)
library(janitor)
```

```{r}
emp_id <- c(1:10)

emp_name <- c("John Mendes", "Rob Stewart", "Rachel Abrahamson", "Christy Hickman", "Johnson Harper", "Candace Miller", "Carlson Landy", "Pansy Jordan", "Darius Berry", "Claudia Garcia")

emp_job_title <- c("Professional", "Programmer", "Management", "Clerical", "Developer", "Programmer", "Management", "Clerical", "Developer", "Programmer")

employee <- data.frame(emp_id, emp_name, emp_job_title) 
employee
str(employee)
```


```{r}
# split emp name into 2 cols first and last
employee_separate <- employee %>% separate(emp_name, into = c('first_name', 'last_name'), sep = ' ')
employee_separate

```

```{r}
# unite emp first and last name
employee_unite <- employee_separate %>% unite('name', first_name, last_name, sep = ' ')
employee_unite

```


```{r}
# mutate to add new col
install.packages("palmerpenguins")
library(palmerpenguins)
# data(package = 'palmerpenguins')
str(penguins)
penguins <- penguins %>% 
  mutate(body_mass_kg = body_mass_g/1000, flipper_length_m = flipper_length_mm/1000)
penguins
```

```{r}
# use the arrange() function to sort the data for the column bill_length_mm in ascending order
penguins <- penguins %>%  arrange(bill_length_mm)
penguins
```

```{r}
# What code chunk does the analyst add to create a data frame that only includes the Gentoo species? 
penguins_gentoo <- penguins %>%  filter(species == 'Gentoo')
penguins_gentoo
```

```{r}
# Add the code chunk that lets you find the minimum value for the variable bill_depth_mm 
penguins_min <-  penguins %>% drop_na() %>% group_by(species) %>% 
  summarise(min_bill_len = min(bill_depth_mm))
penguins_min
```

```{r}
# install.packages("SimDesign")
library(SimDesign)

actual_temp <- c(68.3, 70, 72.4, 71, 67, 70) 
predicted_temp <- c(67.9, 69, 71.5, 70, 67, 69) 
bias(actual_temp, predicted_temp)

```

```{r}
actual_sales <- c(150, 203, 137, 247, 116, 287) 
predicted_sales <- c(200, 300, 150, 250, 150, 300) 
bias(actual_sales, predicted_sales)

```


